---
- name: Create a file and add content to it
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Create docker-compose.yml with content
      blockinfile:
        path: /home/docker-compose.yml
        create: yes
        block: |
          version: '3.3'

          services:
            db:
              image: mysql:5.7
              volumes:
                - ./mysql:/var/lib/mysql
              restart: always
              environment:
                MYSQL_ROOT_PASSWORD: admin
                MYSQL_DATABASE: database
                MYSQL_USER: admin
                MYSQL_PASSWORD: admin
            wordpress:
              depends_on:
                - db
              image: wordpress:php7.4-apache
              ports:
                - "80:80"
                - "443:443"
              restart: always
              environment:
                WORDPRESS_DB_HOST: db
                WORDPRESS_DB_USER: admin
                WORDPRESS_DB_PASSWORD: admin
                WORDPRESS_DB_NAME: database
              volumes:
                - ./app:/var/www/html

    - name: Run Docker Compose
      command: docker compose up -d
      args:
        chdir: /home